#Requires -Version 7.0
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)][ValidateSet('openai-deepseek', 'anthropic-deepseek', 'anthropic-only')][string]$Template,
    [string]$Path,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Non-interactive generator for the operator profile that Council.Profile.ps1
# reads from %USERPROFILE%\.bsl-flow\config.yaml / $HOME/.bsl-flow/config.yaml
# (overridable with BSL_FLOW_USER_CONFIG). It writes only allowlisted profile
# keys (llm.providers.<name>.{protocol,base_url,token_env},
# llm.models.<name>.{provider,model,effort,cost_estimate_usd},
# review.council.roles.<role>.model) so the generated file passes
# Assert-BSLFlowUserProfileConfig unchanged. Concrete model ids are left as
# REPLACE-ME placeholders: the operator, not the project template, chooses
# them.

function Resolve-BFUserConfigDefaultPath {
    $override = [System.Environment]::GetEnvironmentVariable('BSL_FLOW_USER_CONFIG')
    if (-not [string]::IsNullOrWhiteSpace($override)) { return [System.IO.Path]::GetFullPath($override) }
    return (Join-Path $HOME '.bsl-flow/config.yaml')
}

# Each provider entry: protocol, base_url, token_env. anthropic_messages is
# being added to the transport in parallel; the shape below is future-proof
# for it (Assert-BSLFlowUserProfileConfig validates keys, not protocol values).
$providerCatalog = [ordered]@{
    openai    = [ordered]@{ protocol = 'openai_responses'; base_url = 'https://api.openai.com/v1'; token_env = 'OPENAI_API_KEY' }
    deepseek  = [ordered]@{ protocol = 'openai_compatible'; base_url = 'https://api.deepseek.com'; token_env = 'DEEPSEEK_API_KEY' }
    anthropic = [ordered]@{ protocol = 'anthropic_messages'; base_url = 'https://api.anthropic.com'; token_env = 'ANTHROPIC_API_KEY' }
}

# model profile -> (provider, placeholder model id, effort). Critics
# (review-fast) and the chair (review-chair) are always bound to different
# providers or, for the single-provider template, different placeholder
# model ids: the council independence rule requires critics and chair to
# resolve to distinct models.
$templates = [ordered]@{
    'openai-deepseek'    = [ordered]@{
        providers = @('openai', 'deepseek')
        models    = [ordered]@{
            'review-fast'   = [ordered]@{ provider = 'deepseek'; model = 'deepseek/REPLACE-ME-fast'; effort = 'medium' }
            'review-strong' = [ordered]@{ provider = 'openai'; model = 'openai/REPLACE-ME-strong'; effort = 'high' }
            'review-chair'  = [ordered]@{ provider = 'openai'; model = 'openai/REPLACE-ME-chair'; effort = 'high' }
        }
    }
    'anthropic-deepseek' = [ordered]@{
        providers = @('anthropic', 'deepseek')
        models    = [ordered]@{
            'review-fast'   = [ordered]@{ provider = 'deepseek'; model = 'deepseek/REPLACE-ME-fast'; effort = 'medium' }
            'review-strong' = [ordered]@{ provider = 'anthropic'; model = 'anthropic/REPLACE-ME-strong'; effort = 'high' }
            'review-chair'  = [ordered]@{ provider = 'anthropic'; model = 'anthropic/REPLACE-ME-chair'; effort = 'high' }
        }
    }
    'anthropic-only'     = [ordered]@{
        providers = @('anthropic')
        models    = [ordered]@{
            'review-fast'   = [ordered]@{ provider = 'anthropic'; model = 'anthropic/REPLACE-ME-fast'; effort = 'medium' }
            'review-strong' = [ordered]@{ provider = 'anthropic'; model = 'anthropic/REPLACE-ME-strong'; effort = 'high' }
            'review-chair'  = [ordered]@{ provider = 'anthropic'; model = 'anthropic/REPLACE-ME-chair'; effort = 'high' }
        }
    }
}

$selected = $templates[$Template]
$targetPath = if ([string]::IsNullOrWhiteSpace($Path)) { Resolve-BFUserConfigDefaultPath } else { [System.IO.Path]::GetFullPath($Path) }

if ((Test-Path -LiteralPath $targetPath -PathType Leaf) -and -not $Force) {
    throw "BF_BLOCKED: user profile config already exists: $targetPath. Pass -Force to overwrite, or edit it directly."
}
if (Test-Path -LiteralPath $targetPath -PathType Container) { throw "A directory exists where the user profile config file is expected: $targetPath" }

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# BSL Flow user profile config, generated by scripts/New-BSLFlowUserConfig.ps1')
$lines.Add("# Template: $Template")
$lines.Add('#')
$lines.Add('# Every "REPLACE-ME" model id below is a placeholder: replace it with the')
$lines.Add('# actual model id your provider account exposes before running a council')
$lines.Add('# review. Nothing here is read by the versioned project bsl-flow.yaml; only')
$lines.Add('# this file (or the path in BSL_FLOW_USER_CONFIG) binds review-fast,')
$lines.Add('# review-strong and review-chair to real providers and models. Never add a')
$lines.Add('# literal token or Authorization header here: use token_env plus an')
$lines.Add('# environment variable, or the .bsl-flow/providers.local.yaml overlay.')
$lines.Add('# anthropic_messages uses forced tool_choice: select a model that supports')
$lines.Add('# forced tools. An HTTP 400 rejection is a provider capability failure;')
$lines.Add('# inspect the response and change the model binding instead of bypassing validation.')
$lines.Add('llm:')
$lines.Add('  providers:')
foreach ($providerName in $selected.providers) {
    $provider = $providerCatalog[$providerName]
    $lines.Add("    ${providerName}:")
    $lines.Add("      protocol: $($provider.protocol)")
    $lines.Add("      base_url: $($provider.base_url)")
    $lines.Add("      token_env: $($provider.token_env)")
}
$lines.Add('  models:')
foreach ($modelName in $selected.models.Keys) {
    $model = $selected.models[$modelName]
    $lines.Add("    ${modelName}:")
    $lines.Add("      provider: $($model.provider)")
    $lines.Add("      model: $($model.model)")
    $lines.Add("      effort: $($model.effort)")
}
$lines.Add('review:')
$lines.Add('  council:')
$lines.Add('    roles:')
foreach ($role in @('intent_critic', 'architecture_critic', 'executability_critic')) {
    $lines.Add("      ${role}:")
    $lines.Add('        model: review-fast')
}
$lines.Add('      brainstorm:')
$lines.Add('        model: review-strong')
$lines.Add('      chair:')
$lines.Add('        model: review-chair')

$content = ($lines -join "`n") + "`n"

if ($PSCmdlet.ShouldProcess($targetPath, "Write BSL Flow user profile config ($Template)")) {
    [System.IO.Directory]::CreateDirectory((Split-Path -Parent $targetPath)) | Out-Null
    $utf8 = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($targetPath, $content, $utf8)
    [pscustomobject]@{ path = $targetPath; template = $Template; written = $true }
}
else {
    [pscustomobject]@{ path = $targetPath; template = $Template; written = $false }
}
