#Requires -Version 7.0
[CmdletBinding()]
param([string]$PackageRoot)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(-not $PackageRoot){$PackageRoot=Split-Path $PSScriptRoot -Parent}
$core=Join-Path $PackageRoot 'global/skills/1c-task/scripts'
foreach($name in @('Task.Storage.ps1','Task.Contracts.ps1','Task.Gates.ps1','Task.Process.ps1','Task.Engine.ps1','Task.Stages.ps1','Task.Delivery.ps1')){. (Join-Path $core $name)}
$script:checks=0
function Assert-D([bool]$Value,[string]$Message){if(-not $Value){throw "ASSERTION FAILED: $Message"};$script:checks++}
function Expect-D([scriptblock]$Action,[string]$Prefix,[string]$Message){$actual='';try{& $Action|Out-Null}catch{$actual=$_.Exception.Message};Assert-D ($actual.StartsWith($Prefix+':')) "$Message Observed: $actual"}
function Write-D([string]$Path,[string]$Text){[void][IO.Directory]::CreateDirectory((Split-Path $Path -Parent));[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
$testRoot=Join-Path ([IO.Path]::GetTempPath()) ('bsl-flow-task-delivery-'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($testRoot)
try {
 $project=Join-Path $testRoot 'project';[void][IO.Directory]::CreateDirectory($project);[void](Invoke-BFGit $project @('init'));Write-D (Join-Path $project 'hello.txt') "Initial`n";Write-D (Join-Path $project 'obsolete.txt') "obsolete`n";Write-D (Join-Path $project '.gitignore') ".bsl-flow/`nopenspec/changes/`n";[void](Invoke-BFGit $project @('add','.'));[void](Invoke-BFGit $project @('-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','Fixture'))
 $request=[pscustomobject]@{schema_version=1;request_id=[guid]::NewGuid().ToString();prompt='Replace fixture source.';mode='implement';analysis_goal='analysis';complexity='S';risk='low';impact_flags=@();criteria=@([pscustomobject]@{id='source';observation='Greeting exists.';kind='file_assertion';path='hello.txt';contains='Accepted'});provenance=[pscustomobject]@{source='user';reference='delivery-test';text='Fixture.'};models=[pscustomobject]@{worker='gpt-6-astra';worker_effort='medium';reviewer='gpt-6-astra';reviewer_effort='high'}}
 $task=Start-BFTask $project $request
 $executor={param($run);switch($run.attempt.stage){'inspect'{$payload=Get-BFCanonicalJson ([ordered]@{complexity='S';risk='low';impact_flags=@();rationale='Fixture.'})}'implement'{Write-D (Join-Path $run.state.worker_path 'hello.txt') "Accepted`n";Remove-Item -LiteralPath (Join-Path $run.state.worker_path 'obsolete.txt');$payload='{"changed_files":["hello.txt","obsolete.txt"]}'}'verify'{return Invoke-BFVerification $run.state (Join-Path $run.directory 'raw') '' $null}default{throw 'Unexpected stage.'}};[ordered]@{schema_version=1;status='completed';summary='Fixture complete.';payload_json=$payload}}
 $task=Invoke-BFRun $project $task.task_id '' $executor;Assert-D ($task.status -eq 'completed') 'Stub stages did not complete.';$task=Accept-BFTask $project $task.task_id
 $handoff=Export-BFTaskDelivery $project $task.task_id;Assert-D (-not $handoff.idempotent -and (Test-Path -LiteralPath (Join-Path $handoff.path 'source/hello.txt'))) 'Initial handoff missing source.';Assert-D (-not (Test-Path -LiteralPath (Join-Path $handoff.path 'source/obsolete.txt'))) 'Deleted source was copied.';$deleted=@((Read-BFJson (Join-Path $handoff.path 'source-manifest.json')).files|Where-Object{$_.path -eq 'obsolete.txt'});Assert-D ($deleted.Count -eq 1 -and $deleted[0].deleted) 'Deletion missing from manifest.'
 $repeat=Export-BFTaskDelivery $project $task.task_id;Assert-D ($repeat.idempotent -and $repeat.path -eq $handoff.path) 'Exact repeat was not idempotent.'
 Write-D (Join-Path $task.worker_path 'hello.txt') "Drifted`n";Expect-D {Export-BFTaskDelivery $project $task.task_id} 'BF_BLOCKED' 'Source drift was accepted.';Write-D (Join-Path $task.worker_path 'hello.txt') "Accepted`n"
 $handoffPath=Join-Path $handoff.path 'handoff.json';$originalHandoff=[IO.File]::ReadAllText($handoffPath);$editedHandoff=Read-BFJson $handoffPath;$editedHandoff.acceptance_copy_sha256='0'*64;Write-D $handoffPath (Get-BFCanonicalJson $editedHandoff);Expect-D {Export-BFTaskDelivery $project $task.task_id} 'BF_CONFLICT' 'Tampered copy hash was accepted.';Write-D $handoffPath $originalHandoff
 $receiptPath=$task.acceptances[-1].path;$originalReceipt=[IO.File]::ReadAllText($receiptPath);[IO.File]::AppendAllText($receiptPath,' ');Expect-D {Export-BFTaskDelivery $project $task.task_id} 'BF_CONFLICT' 'Changed raw receipt bytes matched the existing handoff.';Write-D $receiptPath $originalReceipt
 $editedReceipt=Read-BFJson $receiptPath;$editedReceipt.verdict='FAIL';Write-D $receiptPath (Get-BFCanonicalJson $editedReceipt);Expect-D {Export-BFTaskDelivery $project $task.task_id} 'BF_BLOCKED' 'Semantically tampered receipt was accepted.'
 $other=Start-BFTask $project ([pscustomobject]@{schema_version=1;request_id=[guid]::NewGuid().ToString();prompt='Unfinished.';mode='implement';analysis_goal='analysis';complexity='S';risk='low';impact_flags=@();criteria=@([pscustomobject]@{id='source';observation='Greeting exists.';kind='file_assertion';path='hello.txt';contains='Accepted'});provenance=$request.provenance;models=$request.models});Expect-D {Export-BFTaskDelivery $project $other.task_id} 'BF_BLOCKED' 'Unaccepted task was delivered.'
 Write-Host "Task delivery: $script:checks checks PASS."
} finally { $safe=[IO.Path]::GetFullPath($testRoot);$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar;if(-not $safe.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase) -or [IO.Path]::GetFileName($safe) -notmatch '^bsl-flow-task-delivery-'){throw "Unsafe delivery test cleanup target: $safe"};if(Test-Path -LiteralPath $safe){Remove-Item -LiteralPath $safe -Recurse -Force} }
